/* What a package manager does to run a maintainer script, reduced to the two
 * things that answered wrongly under chroot-ng on a real device.
 *
 * 1. The empty pathname. Every dpkg maintainer script generated by
 *    dh_installmenu opens with `[ -x "$(command -v update-menus)" ]`, which
 *    for a program that is not installed is `[ -x "" ]`. The kernel answers
 *    ENOENT for an empty path on every path-bearing syscall; resolving it as
 *    the working directory instead makes the test true, and the script goes on
 *    to run a program that does not exist (exit 127).
 *
 * 2. fchdir(root_fd) and then execve of a RELATIVE path — apk's
 *    apk_db_run_script, and the route it takes on any kernel without
 *    /proc/sys/vm/memfd_noexec (below 6.3, which is most devices). The virtual
 *    working directory has to follow the fchdir, or the script name resolves
 *    under wherever the cwd was left standing.
 *
 * Run as `scriptprobe [relpath]`: with an argument, re-executes itself through
 * that relative path after the fchdir, and the re-execed copy prints the
 * relexec line. Every line is a fixed string so the whole output can be
 * compared against the oracle's.
 */
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>

/* Name the errno rather than print it: the numbers agree across these libcs,
 * but a name is what makes a failing diff readable. */
static const char *how(long r) {
    if (r >= 0)
        return "OK";
    switch (errno) {
    case ENOENT: return "ENOENT";
    case EACCES: return "EACCES";
    case EINVAL: return "EINVAL";
    case ELOOP:  return "ELOOP";
    case ENOTDIR: return "ENOTDIR";
    default:     return "OTHER";
    }
}

int main(int argc, char **argv) {
    if (argc > 1 && strcmp(argv[1], "child") == 0) {
        printf("relexec=SCRIPT-OK\n");
        fflush(stdout);
        return 0;
    }

    struct stat st;
    printf("empty-access=%s\n", how(access("", X_OK)));
    printf("empty-stat=%s\n", how(stat("", &st)));
    printf("empty-open=%s\n", how(open("", O_RDONLY)));

    if (argc < 2) {
        fflush(stdout);
        return 0;
    }

    int root = open("/", O_RDONLY | O_DIRECTORY);
    if (root < 0 || fchdir(root) != 0) {
        printf("fchdir=failed\n");
        fflush(stdout);
        return 1;
    }
    char cwd[4096];
    printf("fchdir-cwd=%s\n", getcwd(cwd, sizeof cwd) ? cwd : "(failed)");
    fflush(stdout); /* before the fork, so the buffer is not printed twice */

    pid_t pid = fork();
    if (pid == 0) {
        char *av[] = {(char *)"scriptprobe", (char *)"child", NULL};
        char *ev[] = {NULL};
        execve(argv[1], av, ev);
        printf("relexec=%s\n", how(-1));
        fflush(stdout);
        _exit(127);
    }
    int status = 0;
    waitpid(pid, &status, 0);
    printf("relexec-rc=%d\n", WIFEXITED(status) ? WEXITSTATUS(status) : -1);
    fflush(stdout);
    return 0;
}
