/* What a package manager does to run a maintainer script, reduced to the two
 * things that answered wrongly under chroot-ng on a real device.
 *
 * 1. The empty pathname. Every dpkg maintainer script generated by
 *    dh_installmenu opens with `[ -x "$(command -v update-menus)" ]`, which
 *    for a program that is not installed is `[ -x "" ]`. The kernel answers
 *    ENOENT for an empty path on every path-bearing syscall; resolving it as
 *    the working directory instead makes the test true, and the script goes on
 *    to run a program that does not exist (exit 127).
 *
 * 2. fchdir(root_fd) and then execve of a RELATIVE path — apk's
 *    apk_db_run_script, and the route it takes on any kernel without
 *    /proc/sys/vm/memfd_noexec (below 6.3, which is most devices). The virtual
 *    working directory has to follow the fchdir, or the script name resolves
 *    under wherever the cwd was left standing.
 *
 * 3. The two file shapes the exec path has to tell apart without reading a
 *    whole ELF header. A `#!` script is routinely shorter than the 64 bytes an
 *    Elf64_Ehdr occupies (debconf's extracted .config scripts are ~50), so the
 *    shebang probe must not depend on one read returning everything it asked
 *    for; and a genuinely empty file is ENOEXEC, the same as on the kernel.
 *
 * Run as `scriptprobe [relpath [shortscript emptyfile]]`: with an argument,
 * re-executes itself through that relative path after the fchdir, and the
 * re-execed copy prints the relexec line. Every line is a fixed string so the
 * whole output can be compared against the oracle's.
 */
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>

/* Upper bound on the argv `manyargv` builds. Well past any fixed cap the exec
 * emulation might have, and small enough to stay inside every ARG_MAX. */
#define MANY_MAX 1000

/* Name the errno rather than print it: the numbers agree across these libcs,
 * but a name is what makes a failing diff readable. */
static const char *how(long r) {
    if (r >= 0)
        return "OK";
    switch (errno) {
    case ENOENT: return "ENOENT";
    case ENOEXEC: return "ENOEXEC";
    case EACCES: return "EACCES";
    case EINVAL: return "EINVAL";
    case ELOOP:  return "ELOOP";
    case ENOTDIR: return "ENOTDIR";
    default:     return "OTHER";
    }
}

int main(int argc, char **argv) {
    if (argc > 1 && strcmp(argv[1], "child") == 0) {
        printf("relexec=SCRIPT-OK\n");
        fflush(stdout);
        return 0;
    }
    /* Reached as the interpreter of the short script below, whose shebang
     * line is "#!/scriptprobe shortok" — this binary is the only interpreter
     * the synthetic test rootfs has. */
    if (argc > 1 && strcmp(argv[1], "shortok") == 0) {
        printf("shortscript=SCRIPT-OK\n");
        fflush(stdout);
        return 0;
    }
    /* Reached as the interpreter of a script whose `#!` line carries the
     * argument "argok". Print the whole argv the interpreter was handed: what
     * the kernel splices in is {interpreter, argument, script path} and
     * nothing else, so anything extra — or an argument that kept the line's
     * trailing blanks — shows up here. */
    if (argc > 1 && strncmp(argv[1], "argok", 5) == 0) {
        printf("shebargv=");
        for (int i = 1; i < argc; i++)
            printf("[%s]", argv[i]);
        printf("\n");
        fflush(stdout);
        return 0;
    }
    /* Same thing counted rather than printed, for the leg that hands a script
     * more arguments than fit on one line of output. A #! exec must carry all
     * of them: the kernel bounds argv by bytes, never by entry count. */
    if (argc > 1 && strcmp(argv[1], "argcount") == 0) {
        printf("shebargc=%d\n", argc);
        fflush(stdout);
        return 0;
    }
    /* `scriptprobe manyargv SCRIPT N` — exec SCRIPT with an argv of N entries,
     * which is how a shell expands a glob onto a script. The interpreter should
     * then see N + 2: its own name, the argument off the #! line and the script
     * path replace argv[0], and argv[1..N-1] follow. */
    if (argc > 3 && strcmp(argv[1], "manyargv") == 0) {
        int n = atoi(argv[3]);
        if (n < 1 || n > MANY_MAX)
            n = 1;
        static char slots[MANY_MAX][12];
        static char *av[MANY_MAX + 1];
        for (int i = 0; i < n; i++) {
            snprintf(slots[i], sizeof slots[i], "a%d", i);
            av[i] = slots[i];
        }
        av[n] = 0;
        char *ev[] = {(char *)"SHEBENV=x", NULL};
        fflush(stdout);
        execve(argv[2], av, ev);
        printf("manyargv=%s\n", how(-1));
        fflush(stdout);
        return 125;
    }

    struct stat st;
    printf("empty-access=%s\n", how(access("", X_OK)));
    printf("empty-stat=%s\n", how(stat("", &st)));
    printf("empty-open=%s\n", how(open("", O_RDONLY)));

    if (argc < 2) {
        fflush(stdout);
        return 0;
    }

    int root = open("/", O_RDONLY | O_DIRECTORY);
    if (root < 0 || fchdir(root) != 0) {
        printf("fchdir=failed\n");
        fflush(stdout);
        return 1;
    }
    char cwd[4096];
    printf("fchdir-cwd=%s\n", getcwd(cwd, sizeof cwd) ? cwd : "(failed)");
    fflush(stdout); /* before the fork, so the buffer is not printed twice */

    pid_t pid = fork();
    if (pid == 0) {
        char *av[] = {(char *)"scriptprobe", (char *)"child", NULL};
        char *ev[] = {NULL};
        execve(argv[1], av, ev);
        printf("relexec=%s\n", how(-1));
        fflush(stdout);
        _exit(127);
    }
    int status = 0;
    waitpid(pid, &status, 0);
    printf("relexec-rc=%d\n", WIFEXITED(status) ? WEXITSTATUS(status) : -1);
    fflush(stdout);

    /* argv[2]: a `#!` script shorter than an ELF header, which must run.
     * argv[3]: an empty file, which must be ENOEXEC. Each in its own child,
     * since a successful exec does not come back. */
    for (int i = 2; i < argc && i <= 3; i++) {
        const char *label = i == 2 ? "shortscript" : "emptyfile";
        fflush(stdout);
        pid = fork();
        if (pid == 0) {
            char *av[] = {(char *)argv[i], NULL};
            char *ev[] = {NULL};
            execve(argv[i], av, ev);
            printf("%s=%s\n", label, how(-1));
            fflush(stdout);
            _exit(126);
        }
        status = 0;
        waitpid(pid, &status, 0);
        printf("%s-rc=%d\n", label,
               WIFEXITED(status) ? WEXITSTATUS(status) : -1);
        fflush(stdout);
    }

    /* argv[4]: a `#!` script exec'd with an EMPTY argv. Legal — the kernel's
     * remove_arg_zero has nothing to remove and simply splices the three
     * entries in — and the one case where "the caller's argv from [1] on"
     * reads past the vector's own terminator. The environment is deliberately
     * not empty: it is laid out directly behind argv, so it is what an
     * over-running walk picks up. */
    if (argc > 4) {
        fflush(stdout);
        pid = fork();
        if (pid == 0) {
            char *av[] = {NULL};
            char *ev[] = {(char *)"SHEBENV=x", NULL};
            execve(argv[4], av, ev);
            printf("noargv=%s\n", how(-1));
            fflush(stdout);
            _exit(125);
        }
        status = 0;
        waitpid(pid, &status, 0);
        fflush(stdout);
    }
    return 0;
}
